# Generated by Django 4.2.6 on 2024-04-13 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0004_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='to_pay',
            new_name='amount',
        ),
        migrations.AddField(
            model_name='address',
            name='order_id',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
