# Generated by Django 4.2.6 on 2024-04-13 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0005_rename_to_pay_address_amount_address_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='mob',
            field=models.IntegerField(default=9999999999, max_length=10),
        ),
        migrations.AlterField(
            model_name='address',
            name='pin',
            field=models.IntegerField(max_length=6),
        ),
    ]
