# Generated by Django 4.2.6 on 2024-04-13 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0006_alter_address_mob_alter_address_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='pin',
            field=models.IntegerField(max_length=6, null=True),
        ),
    ]
